
CELERY_BROKER_URL_DOCKER = 'amqp://admin:mypass@rabbit:5672/'
CELERY_BROKER_URL_LOCAL = 'amqp://localhost/'


CM_REGISTER_Q = 'rpc_queue_CM_register' # Do no change this value

CM_NAME = 'CM - District heating supply dispatch'
RPC_CM_ALIVE= 'rpc_queue_CM_ALIVE' # Do no change this value
RPC_Q = 'rpc_queue_CM_compute' # Do no change this value
CM_ID = 14 # CM_ID is defined by the enegy research center of Martigny (CREM)
PORT_LOCAL = int('500' + str(CM_ID))
PORT_DOCKER = 80

#TODO ********************setup this URL depending on which version you are running***************************

CELERY_BROKER_URL = CELERY_BROKER_URL_DOCKER
PORT = PORT_DOCKER

#TODO ********************setup this URL depending on which version you are running***************************
TRANFER_PROTOCOLE ='http://'
# =============================================================================
# 
# =============================================================================


INPUTS_CALCULATION_MODULE = [{'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'Thermal Output Capacity  -Back Pressure CHP ',
  'input_parameter_name': 'chp_cap',
  'input_priority': '0',
  'input_type': 'input',
  'input_unit': 'MW',
  'input_value': '0'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'Thermal Output Capacity -Waste Incineration Plant ',
  'input_parameter_name': 'wi_cap',
  'input_priority': '0',
  'input_type': 'input',
  'input_unit': 'MW',
  'input_value': '0'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'Thermal Output Capacity -Heat Boiler ',
  'input_parameter_name': 'hb_cap',
  'input_priority': '0',
  'input_type': 'input',
  'input_unit': 'MW',
  'input_value': '0'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'Thermal Output Capacity  -Heat Pump ',
  'input_parameter_name': 'hp_cap',
  'input_priority': '0',
  'input_type': 'input',
  'input_unit': 'MW',
  'input_value': '0'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'Thermal Output Capacity  -Solar Thermal ',
  'input_parameter_name': 'st_cap',
  'input_priority': '0',
  'input_type': 'input',
  'input_unit': 'MW',
  'input_value': '0'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'CO2 Price ',
  'input_parameter_name': 'pCO2_pCO2',
  'input_priority': '0',
  'input_type': 'input',
  'input_unit': 'EUR/tCO2',
  'input_value': '30'},
 {'cm_id': CM_ID,
  'input_max': '1.0',
  'input_min': '0',
  'input_name': 'interest rate ',
  'input_parameter_name': 'ir_ir',
  'input_priority': '0',
  'input_type': 'input',
  'input_unit': '',
  'input_value': '0.07'},
 {'cm_id': CM_ID,
  'input_max': '',
  'input_min': '',
  'input_name': 'invest mode',
  'input_parameter_name': 'if_if',
  'input_priority': '0',
  'input_type': 'select',
  'input_unit': '',
  'input_value': ['invest', 'dispatch']},
 {'cm_id': CM_ID,
  'input_max': '1.0',
  'input_min': '0',
  'input_name': 'thermal efficiency -Back Pressure CHP ',
  'input_parameter_name': 'chp_nth',
  'input_priority': '1',
  'input_type': 'input',
  'input_unit': '',
  'input_value': '0.6'},
 {'cm_id': CM_ID,
  'input_max': '1.0',
  'input_min': '0',
  'input_name': 'electrical efficiency -Back Pressure CHP ',
  'input_parameter_name': 'chp_nel',
  'input_priority': '1',
  'input_type': 'input',
  'input_unit': '',
  'input_value': '0.2'},
 {'cm_id': CM_ID,
  'input_max': '1.0',
  'input_min': '0',
  'input_name': 'thermal efficiency -Waste Incineration Plant',
  'input_parameter_name': 'wi_nth',
  'input_priority': '1',
  'input_type': 'input',
  'input_unit': '',
  'input_value': '0.6'},
 {'cm_id': CM_ID,
  'input_max': '1.0',
  'input_min': '0',
  'input_name': 'electrical efficiency -Waste Incineration Plant',
  'input_parameter_name': 'wi_nel',
  'input_priority': '1',
  'input_type': 'input',
  'input_unit': '',
  'input_value': '0.2'},
 {'cm_id': CM_ID,
  'input_max': '1.0',
  'input_min': '0',
  'input_name': 'thermal efficiency -Heat Boiler ',
  'input_parameter_name': 'hb_nth',
  'input_priority': '1',
  'input_type': 'input',
  'input_unit': '',
  'input_value': '0.875'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'COP -Heat Pump',
  'input_parameter_name': 'hp_nth',
  'input_priority': '1',
  'input_type': 'input',
  'input_unit': '',
  'input_value': '3'},
 {'cm_id': CM_ID,
  'input_max': '1.0',
  'input_min': '0',
  'input_name': 'thermal efficiency -Solar Thermal ',
  'input_parameter_name': 'st_nth',
  'input_priority': '1',
  'input_type': 'input',
  'input_unit': '',
  'input_value': '1'},
 {'cm_id': CM_ID,
  'input_max': '100.0',
  'input_min': '0',
  'input_name': 'lifetime -Back Pressure CHP ',
  'input_parameter_name': 'chp_lt',
  'input_priority': '1',
  'input_type': 'input',
  'input_unit': 'a',
  'input_value': '25'},
 {'cm_id': CM_ID,
  'input_max': '100.0',
  'input_min': '0',
  'input_name': 'lifetime -Waste Incineration Plant',
  'input_parameter_name': 'wi_lt',
  'input_priority': '1',
  'input_type': 'input',
  'input_unit': 'a',
  'input_value': '25'},
 {'cm_id': CM_ID,
  'input_max': '100.0',
  'input_min': '0',
  'input_name': 'lifetime -Heat Boiler ',
  'input_parameter_name': 'hb_lt',
  'input_priority': '1',
  'input_type': 'input',
  'input_unit': 'a',
  'input_value': '20'},
 {'cm_id': CM_ID,
  'input_max': '100.0',
  'input_min': '0',
  'input_name': 'lifetime -Heat Pump  ',
  'input_parameter_name': 'hp_lt',
  'input_priority': '1',
  'input_type': 'input',
  'input_unit': 'a',
  'input_value': '25'},
 {'cm_id': CM_ID,
  'input_max': '100.0',
  'input_min': '0',
  'input_name': 'lifetime -Solar Thermal ',
  'input_parameter_name': 'st_lt',
  'input_priority': '1',
  'input_type': 'input',
  'input_unit': 'a',
  'input_value': '20'},
 {'cm_id': CM_ID,
  'input_max': '',
  'input_min': '',
  'input_name': 'energy carrier -Back Pressure CHP ',
  'input_parameter_name': 'chp_ec',
  'input_priority': '1',
  'input_type': 'select',
  'input_unit': '',
  'input_value': ['wood pellets',
                  'electricity',
                  'bio gas',
                  'waste',
                  'radiation',
                  'various']},
 {'cm_id': CM_ID,
  'input_max': '',
  'input_min': '',
  'input_name': 'energy carrier -Waste Incineration Plant',
  'input_parameter_name': 'wi_ec',
  'input_priority': '1',
  'input_type': 'select',
  'input_unit': '',
  'input_value': ['waste',
                  'electricity',
                  'bio gas',
                  'wood pellets',
                  'radiation',
                  'various']},
 {'cm_id': CM_ID,
  'input_max': '',
  'input_min': '',
  'input_name': 'energy carrier -Heat Boiler ',
  'input_parameter_name': 'hb_ec',
  'input_priority': '1',
  'input_type': 'select',
  'input_unit': '',
  'input_value': ['bio gas',
                  'electricity',
                  'waste',
                  'wood pellets',
                  'radiation',
                  'various']},
 {'cm_id': CM_ID,
  'input_max': '',
  'input_min': '',
  'input_name': 'energy carrier -Heat Pump  ',
  'input_parameter_name': 'hp_ec',
  'input_priority': '1',
  'input_type': 'select',
  'input_unit': '',
  'input_value': ['electricity',
                  'bio gas',
                  'waste',
                  'wood pellets',
                  'radiation',
                  'various']},
 {'cm_id': CM_ID,
  'input_max': '',
  'input_min': '',
  'input_name': 'energy carrier -Solar Thermal ',
  'input_parameter_name': 'st_ec',
  'input_priority': '1',
  'input_type': 'select',
  'input_unit': '',
  'input_value': ['radiation',
                  'electricity',
                  'bio gas',
                  'waste',
                  'wood pellets',
                  'various']},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '-1e102',
  'input_name': 'emission factor -Bio Gas',
  'input_parameter_name': 'bio gas_ef',
  'input_priority': '2',
  'input_type': 'input',
  'input_unit': 'tCO2/MWh',
  'input_value': '0.202'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '-1e102',
  'input_name': 'emission factor  -waste ',
  'input_parameter_name': 'waste_ef',
  'input_priority': '2',
  'input_type': 'input',
  'input_unit': 'tCO2/MWh',
  'input_value': '0.114'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '-1e102',
  'input_name': 'emission factor  -wood pellets ',
  'input_parameter_name': 'wood pellets_ef',
  'input_priority': '2',
  'input_type': 'input',
  'input_unit': 'tCO2/MWh',
  'input_value': '0.312'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '-1e102',
  'input_name': 'emission factor  -radiation',
  'input_parameter_name': 'radiation_ef',
  'input_priority': '2',
  'input_type': 'input',
  'input_unit': 'tCO2/MWh',
  'input_value': '0'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '-1e102',
  'input_name': 'emission factor  -various ',
  'input_parameter_name': 'various_ef',
  'input_priority': '2',
  'input_type': 'input',
  'input_unit': 'tCO2/MWh',
  'input_value': '0'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '-1e102',
  'input_name': 'emission factor -electricity ',
  'input_parameter_name': 'electricity_ef',
  'input_priority': '2',
  'input_type': 'input',
  'input_unit': 'tCO2/MWh',
  'input_value': '0.09'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '-1e102',
  'input_name': 'energy carrier price - Bio Gas ',
  'input_parameter_name': 'bio gas_p',
  'input_priority': '2',
  'input_type': 'input',
  'input_unit': 'EUR/MWh',
  'input_value': '40'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '-1e102',
  'input_name': 'energy carrier price - waste ',
  'input_parameter_name': 'waste_p',
  'input_priority': '2',
  'input_type': 'input',
  'input_unit': 'EUR/MWh',
  'input_value': '3'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '-1e102',
  'input_name': 'energy carrier price -wood pellets ',
  'input_parameter_name': 'wood pellets_p',
  'input_priority': '2',
  'input_type': 'input',
  'input_unit': 'EUR/MWh',
  'input_value': '44'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '-1e102',
  'input_name': 'energy carrier price -radiation',
  'input_parameter_name': 'radiation_p',
  'input_priority': '2',
  'input_type': 'input',
  'input_unit': 'EUR/MWh',
  'input_value': '0'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '-1e102',
  'input_name': 'energy carrier price - various ',
  'input_parameter_name': 'various_p',
  'input_priority': '2',
  'input_type': 'input',
  'input_unit': 'EUR/MWh',
  'input_value': '22'},
 {'cm_id': CM_ID,
  'input_max': '',
  'input_min': '',
  'input_name': 'electricity price-Back Pressure CHP ',
  'input_parameter_name': 'chp_elpSelect',
  'input_priority': '2',
  'input_type': 'select',
  'input_unit': '',
  'input_value': ['hotmaps default hourly profile', 'fix']},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '-1e102',
  'input_name': 'fix electricity price-Back Pressure CHP ',
  'input_parameter_name': 'chp_elp',
  'input_priority': '2',
  'input_type': 'input',
  'input_unit': 'EUR/MWh',
  'input_value': '45'},
 {'cm_id': CM_ID,
  'input_max': '',
  'input_min': '',
  'input_name': 'sale electricity price-Back Pressure CHP ',
  'input_parameter_name': 'chp_selpSelect',
  'input_priority': '2',
  'input_type': 'select',
  'input_unit': '',
  'input_value': ['hotmaps default hourly profile', 'fix']},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '-1e102',
  'input_name': 'fix sale electricity price-Back Pressure CHP ',
  'input_parameter_name': 'chp_selp',
  'input_priority': '2',
  'input_type': 'input',
  'input_unit': 'EUR/MWh',
  'input_value': '45'},
 {'cm_id': CM_ID,
  'input_max': '',
  'input_min': '',
  'input_name': 'electricity price -Waste Incineration Plant',
  'input_parameter_name': 'wi_elpSelect',
  'input_priority': '2',
  'input_type': 'select',
  'input_unit': '',
  'input_value': ['hotmaps default hourly profile', 'fix']},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '-1e102',
  'input_name': 'fix electricity price -Waste Incineration Plant',
  'input_parameter_name': 'wi_elp',
  'input_priority': '2',
  'input_type': 'input',
  'input_unit': 'EUR/MWh',
  'input_value': '45'},
 {'cm_id': CM_ID,
  'input_max': '',
  'input_min': '',
  'input_name': 'sale electricity price -Waste Incineration Plant',
  'input_parameter_name': 'wi_selpSelect',
  'input_priority': '2',
  'input_type': 'select',
  'input_unit': '',
  'input_value': ['hotmaps default hourly profile', 'fix']},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '-1e102',
  'input_name': 'fix sale electricity price -Waste Incineration Plant',
  'input_parameter_name': 'wi_selp',
  'input_priority': '2',
  'input_type': 'input',
  'input_unit': 'EUR/MWh',
  'input_value': '45'},
 {'cm_id': CM_ID,
  'input_max': '',
  'input_min': '',
  'input_name': 'electricity price -Heat Boiler ',
  'input_parameter_name': 'hb_elpSelect',
  'input_priority': '2',
  'input_type': 'select',
  'input_unit': '',
  'input_value': ['hotmaps default hourly profile', 'fix']},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '-1e102',
  'input_name': 'fix electricity price -Heat Boiler ',
  'input_parameter_name': 'hb_elp',
  'input_priority': '2',
  'input_type': 'input',
  'input_unit': 'EUR/MWh',
  'input_value': '45'},
 {'cm_id': CM_ID,
  'input_max': '',
  'input_min': '',
  'input_name': 'electricity price -Heat Pump ',
  'input_parameter_name': 'hp_elpSelect',
  'input_priority': '2',
  'input_type': 'select',
  'input_unit': '',
  'input_value': ['hotmaps default hourly profile', 'fix']},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '-1e102',
  'input_name': 'fix electricity price -Heat Pump ',
  'input_parameter_name': 'hp_elp',
  'input_priority': '2',
  'input_type': 'input',
  'input_unit': 'EUR/MWh',
  'input_value': '45'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'investment cost -Back Pressure CHP ',
  'input_parameter_name': 'chp_ic',
  'input_priority': '3',
  'input_type': 'input',
  'input_unit': 'EUR/MW',
  'input_value': '800000'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'OPEX fix -Back Pressure CHP ',
  'input_parameter_name': 'chp_opexFix',
  'input_priority': '3',
  'input_type': 'input',
  'input_unit': 'EUR/(MW*yr)',
  'input_value': '46000'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'OPEX var -Back Pressure CHP ',
  'input_parameter_name': 'chp_opexVar',
  'input_priority': '3',
  'input_type': 'input',
  'input_unit': 'EUR/MWh',
  'input_value': '4.5'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '-1e102',
  'input_name': 'ramping cost  -Back Pressure CHP',
  'input_parameter_name': 'chp_ramp',
  'input_priority': '3',
  'input_type': 'input',
  'input_unit': 'EUR/MWh',
  'input_value': '100'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'investment cost -Waste Incineration Plant',
  'input_parameter_name': 'wi_ic',
  'input_priority': '3',
  'input_type': 'input',
  'input_unit': 'EUR/MW',
  'input_value': '3200000'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'OPEX fix -Waste Incineration Plant',
  'input_parameter_name': 'wi_opexFix',
  'input_priority': '3',
  'input_type': 'input',
  'input_unit': 'EUR/(MW*yr)',
  'input_value': '90000'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'OPEX var -Waste Incineration Plant',
  'input_parameter_name': 'wi_opexVar',
  'input_priority': '3',
  'input_type': 'input',
  'input_unit': 'EUR/MWh',
  'input_value': '0.5'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '-1e102',
  'input_name': 'ramping cost  -Waste Incineration Plant',
  'input_parameter_name': 'wi_ramp',
  'input_priority': '3',
  'input_type': 'input',
  'input_unit': 'EUR/MWh',
  'input_value': '100'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'investment cost -Heat Boiler ',
  'input_parameter_name': 'hb_ic',
  'input_priority': '3',
  'input_type': 'input',
  'input_unit': 'EUR/MW',
  'input_value': '60000'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'OPEX fix -Heat Boiler ',
  'input_parameter_name': 'hb_opexFix',
  'input_priority': '3',
  'input_type': 'input',
  'input_unit': 'EUR/(MW*yr)',
  'input_value': '4000'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'OPEX var -Heat Boiler ',
  'input_parameter_name': 'hb_opexVar',
  'input_priority': '3',
  'input_type': 'input',
  'input_unit': 'EUR/MWh',
  'input_value': '1.5'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'investment cost -Heat Pump  ',
  'input_parameter_name': 'hp_ic',
  'input_priority': '3',
  'input_type': 'input',
  'input_unit': 'EUR/MW',
  'input_value': '750000'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'OPEX fix -Heat Pump  ',
  'input_parameter_name': 'hp_opexFix',
  'input_priority': '3',
  'input_type': 'input',
  'input_unit': 'EUR/(MW*yr)',
  'input_value': '34000'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'OPEX var -Heat Pump  ',
  'input_parameter_name': 'hp_opexVar',
  'input_priority': '3',
  'input_type': 'input',
  'input_unit': 'EUR/MWh',
  'input_value': '0.5'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'investment cost -Solar Thermal ',
  'input_parameter_name': 'st_ic',
  'input_priority': '3',
  'input_type': 'input',
  'input_unit': 'EUR/MW',
  'input_value': '1030000'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'OPEX fix -Solar Thermal ',
  'input_parameter_name': 'st_opexFix',
  'input_priority': '3',
  'input_type': 'input',
  'input_unit': 'EUR/(MW*yr)',
  'input_value': '30000'},
 {'cm_id': CM_ID,
  'input_max': '1e+102',
  'input_min': '0',
  'input_name': 'OPEX var -Solar Thermal ',
  'input_parameter_name': 'st_opexVar',
  'input_priority': '3',
  'input_type': 'input',
  'input_unit': 'EUR/MWh',
  'input_value': '0.5'}]





SIGNATURE = {

    "category": "Supply",
    "cm_name": CM_NAME,
    "layers_needed": [
        "heat_density_tot", "nuts_id_number"
    ],
    "type_layer_needed": [
    {"type" : "heat","description" : ""},
    {"type" : "nuts_id_number","description" : ""}
    ],


    "vectors_needed": [
    
    ],
    "cm_url": "Do not add something",
    
    "cm_description": """ This module calculates the cost-minimal operation of a 
    portfolio of heat supply technologies in a defined district heating system 
    for each hour of the year. The inputs to the module are hourly profiles for 
    the heat demand in the network, for the potential heat supply from different 
    sources and for energy carrier prices. Furthermore, cost and efficiency parameters 
    for each technology are required. The module yields the costs of heat supply, 
    the share of energy carriers used and the implied CO2 emissions. The module 
    can also be used to optimise the capacities of installed heat supply technologies""",
    "cm_id": CM_ID,
    
    'inputs_calculation_module': INPUTS_CALCULATION_MODULE,
    
    'authorized_scale' : ["NUTS 3", "NUTS 2","NUTS 1", "NUTS 0","Hectare","LAU 2"]
}
